In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\DELL\Downloads\loan_approval_data.csv")

In [4]:
df

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996.0,NaN,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,72.0,Personal,NaN,Not Graduate,Male,Unemployed,No
996,997.0,3279.0,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,NaN,18361.0,22563.0,12.0,Business,Urban,Graduate,Female,Government,No
997,998.0,15192.0,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,24.0,Home,Rural,Graduate,Male,MNC,No
998,999.0,9083.0,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,36.0,Personal,Urban,Graduate,Male,Private,Yes
999,1000.0,13093.0,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,48.0,Personal,Semiurban,Graduate,NaN,Private,No

In [5]:
df=df.drop_duplicates()

In [6]:
df

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996.0,NaN,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,72.0,Personal,NaN,Not Graduate,Male,Unemployed,No
996,997.0,3279.0,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,NaN,18361.0,22563.0,12.0,Business,Urban,Graduate,Female,Government,No
997,998.0,15192.0,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,24.0,Home,Rural,Graduate,Male,MNC,No
998,999.0,9083.0,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,36.0,Personal,Urban,Graduate,Male,Private,Yes
999,1000.0,13093.0,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,48.0,Personal,Semiurban,Graduate,NaN,Private,No

In [10]:
x=df.drop("Loan_Approved",axis=1)
y=df["Loan_Approved"]

In [12]:
from sklearn.preprocessing import LabelEncoder

# 1. Initialize the encoder
le = LabelEncoder()

# 2. Fit and transform the column in-place
x["Employment_Status"] = le.fit_transform(x["Employment_Status"])
x["Marital_Status"] = le.fit_transform(x["Marital_Status"])
x["Employer_Category"] = le.fit_transform(x["Employer_Category"])
x["Loan_Purpose"] = le.fit_transform(x["Loan_Purpose"])
x["Property_Area"] = le.fit_transform(x["Property_Area"])
x["Gender"] = le.fit_transform(x["Gender"])

In [13]:
x

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category
0,1.0,17795.0,1387.0,1,51.0,0,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,4,2,Not Graduate,0,3
1,2.0,2860.0,2679.0,1,46.0,0,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,1,1,Graduate,2,3
2,3.0,7390.0,2106.0,1,25.0,1,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,5,2,NaN,0,1
3,4.0,13964.0,8173.0,1,40.0,0,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,0,0,Graduate,0,1
4,5.0,13284.0,4223.0,2,31.0,1,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,1,3,Graduate,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996.0,NaN,9092.0,1,58.0,0,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,72.0,4,3,Not Graduate,1,4
996,997.0,3279.0,6356.0,2,58.0,0,1.0,646.0,3.0,0.19,NaN,18361.0,22563.0,12.0,0,2,Graduate,0,1
997,998.0,15192.0,8433.0,0,48.0,1,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,24.0,3,0,Graduate,1,2
998,999.0,9083.0,7380.0,3,50.0,1,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,36.0,4,2,Graduate,1,3
999,1000.0,13093.0,2385.0,1,23.0,0,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,48.0,4,1,Graduate,2,3

In [15]:
df.isnull().sum()

Applicant_ID          50
Applicant_Income      50
Coapplicant_Income    50
Employment_Status     50
Age                   50
Marital_Status        50
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose          50
Property_Area         50
Education_Level       50
Gender                50
Employer_Category     50
Loan_Approved         50
dtype: int64

In [18]:
df=df.dropna(how="all")

In [19]:
df

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996.0,NaN,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,72.0,Personal,NaN,Not Graduate,Male,Unemployed,No
996,997.0,3279.0,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,NaN,18361.0,22563.0,12.0,Business,Urban,Graduate,Female,Government,No
997,998.0,15192.0,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,24.0,Home,Rural,Graduate,Male,MNC,No
998,999.0,9083.0,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,36.0,Personal,Urban,Graduate,Male,Private,Yes
999,1000.0,13093.0,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,48.0,Personal,Semiurban,Graduate,NaN,Private,No

In [20]:
num_cols = [
    'Applicant_Income', 'Coapplicant_Income', 'Age', 'Credit_Score', 
    'Existing_Loans', 'DTI_Ratio', 'Savings', 'Collateral_Value', 
    'Loan_Amount', 'Loan_Term'
]

# Fill missing values with the median of each column
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [21]:
cat_cols = ['Employment_Status', 'Marital_Status', 'Loan_Purpose', 
            'Property_Area', 'Education_Level', 'Gender', 'Employer_Category']

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [24]:
x.isnull().sum()

Applicant_ID          50
Applicant_Income      50
Coapplicant_Income    50
Employment_Status      0
Age                   50
Marital_Status         0
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose           0
Property_Area          0
Education_Level       50
Gender                 0
Employer_Category      0
dtype: int64

In [25]:
x = df.drop(columns=['Loan_Approved'],axis=1)

In [29]:
y=df["Loan_Approved"]

In [30]:
x.isnull().sum()

Applicant_ID          50
Applicant_Income       0
Coapplicant_Income     0
Employment_Status      0
Age                    0
Marital_Status         0
Dependents            50
Credit_Score           0
Existing_Loans         0
DTI_Ratio              0
Savings                0
Collateral_Value       0
Loan_Amount            0
Loan_Term              0
Loan_Purpose           0
Property_Area          0
Education_Level        0
Gender                 0
Employer_Category      0
dtype: int64

In [31]:
x = x.drop(columns=['Applicant_ID'])
x['Dependents'] = x['Dependents'].fillna(x['Dependents'].mode()[0])

In [32]:
x.isnull().sum()

Applicant_Income      0
Coapplicant_Income    0
Employment_Status     0
Age                   0
Marital_Status        0
Dependents            0
Credit_Score          0
Existing_Loans        0
DTI_Ratio             0
Savings               0
Collateral_Value      0
Loan_Amount           0
Loan_Term             0
Loan_Purpose          0
Property_Area         0
Education_Level       0
Gender                0
Employer_Category     0
dtype: int64

In [1]:
from sklearn.linear_model import LogisticRegression

In [4]:
import pandas as pd
df=pd.read_csv(r"C:\Users\DELL\Downloads\loan_approval_data.csv")

In [5]:
x=df.drop("Loan_Approved",axis=1)
y=df["Loan_Approved"]

In [11]:
from sklearn.preprocessing import LabelEncoder

# 1. Initialize the encoder
le = LabelEncoder()

# 2. Fit and transform the column in-place
x["Employment_Status"] = le.fit_transform(x["Employment_Status"])
x["Marital_Status"] = le.fit_transform(x["Marital_Status"])
x["Employer_Category"] = le.fit_transform(x["Employer_Category"])
x["Loan_Purpose"] = le.fit_transform(x["Loan_Purpose"])
x["Property_Area"] = le.fit_transform(x["Property_Area"])
x["Gender"] = le.fit_transform(x["Gender"])

In [10]:
num_cols = [
    'Applicant_Income', 'Coapplicant_Income', 'Age', 'Credit_Score', 
    'Existing_Loans', 'DTI_Ratio', 'Savings', 'Collateral_Value', 
    'Loan_Amount', 'Loan_Term'
]

# Fill missing values with the median of each column
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [12]:
cat_cols = ['Employment_Status', 'Marital_Status', 'Loan_Purpose', 
            'Property_Area', 'Education_Level', 'Gender', 'Employer_Category']

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [13]:
x.isnull().sum()

Applicant_ID          50
Applicant_Income      50
Coapplicant_Income    50
Employment_Status      0
Age                   50
Marital_Status         0
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose           0
Property_Area          0
Education_Level       50
Gender                 0
Employer_Category      0
dtype: int64

In [3]:
x = x.drop(columns=['Applicant_ID'])
x['Dependents'] = x['Dependents'].fillna(x['Dependents'].mode()[0])

NameError: name 'x' is not defined

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    
    x, y, test_size=0.2, random_state=42)

NameError: name 'x' is not defined

In [ ]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
x_train_scaled=x_train.fit_transform()
x_test_scaled=x_test.transform()